# UJIAN TENGAH SEMESTER (UTS)
## Visualisasi Data Praktik Mandiri Berbasis Google Colab

* **Mata Kuliah:** Visualisasi Data (3 SKS)
* **Program Studi:** S1 Informatika - UIN K.H. Abdurrahman Wahid Pekalongan
* **Nama Mahasiswa:** Gathan Hilabi
* **NIM:** 60324059
* **Kelas:** Visualisasi Data (A)
* **Studi Kasus:** Gempa Bumi Dirasakan di Indonesia (Data BMKG hingga 13 Oktober 2026)

In [2]:
# Sel awal (wajib dijalankan pertama)
from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import io

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')
  df_uploaded = pd.read_csv(io.BytesIO(uploaded[fn]))

df_uploaded.head()

User uploaded file "dataset_UTS_gempa_dirasakan_bmkg.csv" with length 598431 bytes

,id_gempa,waktu_utc,tahun,bulan,tanggal,lintang,bujur,magnitudo,kedalaman_km,lokasi,jenis_lokasi,dirasakan_di,catatan_kualitas
0,20221214195822,2022-12-14 12:58:22,2022,12,14,-7.50,106.76,3.9,24,Pusat gempa berada di laut 61 km Tenggara Kab....,Laut,II - III Sukabumi,NaN
1,20221214231338,2022-12-14 16:13:38,2022,12,14,-3.72,127.90,3.0,10,Pusat gempa berada di laut 31 km barat Ambon,Laut,II Hative Besar,NaN
2,20221215103109,2022-12-15 03:31:09,2022,12,15,2.88,127.50,5.0,13,Pusat gempa berada di laut 127 km BaratLaut Da...,Laut,II Morotai Selatan,NaN
3,20221215151321,2022-12-15 08:13:21,2022,12,15,-8.22,115.61,3.6,12,Pusat gempa berada di laut 17 km TimurLaut Kar...,Laut,"II Karangasem, II Tejakula",NaN
4,20221215164554,2022-12-15 09:45:54,2022,12,15,-8.23,115.57,4.1,10,Pusat gempa berada di laut 14 km Timurlaut Kar...,Laut,"II - III Karangasem, II Lombok Barat",NaN

---
## B1. Memuat dan Memahami Data (8 Poin)
**Ketentuan Soal:**
* Muat data ke DataFrame `df`. Tampilkan jumlah baris dan kolom (`shape`), 5 baris pertama, dan ringkasan `info()`.
* Pada sel Markdown jawab:
  1. Jumlah baris dan kolom;
  2. Kolom mana saja yang memiliki nilai kosong beserta jumlahnya;
  3. Arti nilai kosong pada kolom `catatan_kualitas`.

In [3]:
# Muat data ke DataFrame df
df = df_uploaded.copy()

# 1. Tampilkan jumlah baris dan kolom (shape)
print("=" * 60)
print(f"Bentuk data (shape): {df.shape[0]} baris x {df.shape[1]} kolom")
print("=" * 60)

# 2. Tampilkan 5 baris pertama
print("\n--- 5 Baris Pertama Data Gempa ---")
display(df.head())

# 3. Tampilkan ringkasan info()
print("\n--- Ringkasan Struktur Data (df.info()) ---")
df.info()

# 4. Tampilkan jumlah nilai kosong per kolom
print("\n--- Jumlah Nilai Kosong per Kolom ---")
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

============================================================
Bentuk data (shape): 3630 baris x 13 kolom
============================================================

--- 5 Baris Pertama Data Gempa ---

,id_gempa,waktu_utc,tahun,bulan,tanggal,lintang,bujur,magnitudo,kedalaman_km,lokasi,jenis_lokasi,dirasakan_di,catatan_kualitas
0,20221214195822,2022-12-14 12:58:22,2022,12,14,-7.50,106.76,3.9,24,Pusat gempa berada di laut 61 km Tenggara Kab....,Laut,II - III Sukabumi,NaN
1,20221214231338,2022-12-14 16:13:38,2022,12,14,-3.72,127.90,3.0,10,Pusat gempa berada di laut 31 km barat Ambon,Laut,II Hative Besar,NaN
2,20221215103109,2022-12-15 03:31:09,2022,12,15,2.88,127.50,5.0,13,Pusat gempa berada di laut 127 km BaratLaut Da...,Laut,II Morotai Selatan,NaN
3,20221215151321,2022-12-15 08:13:21,2022,12,15,-8.22,115.61,3.6,12,Pusat gempa berada di laut 17 km TimurLaut Kar...,Laut,"II Karangasem, II Tejakula",NaN
4,20221215164554,2022-12-15 09:45:54,2022,12,15,-8.23,115.57,4.1,10,Pusat gempa berada di laut 14 km Timurlaut Kar...,Laut,"II - III Karangasem, II Lombok Barat",NaN

--- Ringkasan Struktur Data (df.info()) ---
<class 'pandas.DataFrame'>
RangeIndex: 3630 entries, 0 to 3629
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_gempa          3630 non-null   int64
 1   waktu_utc         3630 non-null   str
 2   tahun             3630 non-null   int64
 3   bulan             3630 non-null   int64
 4   tanggal           3630 non-null   int64
 5   lintang           3630 non-null   float64
 6   bujur             3630 non-null   float64
 7   magnitudo         3630 non-null   float64
 8   kedalaman_km      3630 non-null   int64
 9   lokasi            3630 non-null   str
 10  jenis_lokasi      3613 non-null   str
 11  dirasakan_di      3619 non-null   str
 12  catatan_kualitas  11 non-null     str
dtypes: float64(3), int64(5), str(5)
memory usage: 368.8 KB

--- Jumlah Nilai Kosong per Kolom ---
jenis_lokasi          17
dirasakan_di          11
catatan_kualitas    3619
dtype: int64

### Jawaban dan Analisis B1:
1. **Jumlah Baris dan Kolom:**
   * Dataset memiliki **3.630 baris** kejadian gempa dan **13 kolom** atribut (`shape = (3630, 13)`).
2. **Kolom yang Memiliki Nilai Kosong beserta Jumlahnya:**
   * `jenis_lokasi`: **17 baris** kosong (NaN)
   * `dirasakan_di`: **11 baris** kosong (NaN)
   * `catatan_kualitas`: **3.619 baris** kosong (NaN)
   *(Kolom-kolom lainnya terisi lengkap tanpa ada data yang kosong).*
3. **Arti Nilai Kosong pada Kolom `catatan_kualitas`:**
   * Nilai kosong pada kolom `catatan_kualitas` menandakan bahwa baris rekaman gempa tersebut **tidak memiliki catatan kendala sensor maupun anomali kualitas data** dari kurator BMKG (status datanya normal dan valid).
   * Nilai kosong ini **bukan data hilang atau data rusak yang harus dihapus**, melainkan penanda bahwa data tersebut memenuhi standar pemantauan operasional BMKG. Hanya ada 11 baris dalam dataset yang memiliki catatan anomali, yaitu berstatus `"FUTURE_EARTHQUAKE"`.

---
## B2. Pembersihan Data (14 Poin)
**Ketentuan Soal:**
Lakukan langkah berikut secara berurutan. Simpan hasil akhirnya pada DataFrame `df_bersih` dan gunakan untuk seluruh soal selanjutnya:
1. Buang baris yang pada kolom `catatan_kualitas` bernilai `"FUTURE_EARTHQUAKE"`. Berapa baris yang dibuang?
2. Jalankan `describe()` pada kolom `lintang` dan `bujur`. Temukan nilai yang mustahil untuk wilayah Indonesia (acuan: bujur wajar berada pada 90°–145° BT), buang barisnya, dan jelaskan alasan Anda.
3. Periksa duplikasi berdasarkan `id_gempa` dan laporkan hasilnya.
4. Isi nilai kosong pada `jenis_lokasi` dengan `"Tidak diketahui"`. Laporkan jumlah baris `df_bersih`.

In [4]:
# Langkah 1: Buang baris dengan catatan_kualitas == "FUTURE_EARTHQUAKE"
baris_awal = len(df)
baris_future = (df['catatan_kualitas'] == 'FUTURE_EARTHQUAKE').sum()
df_bersih = df[df['catatan_kualitas'] != 'FUTURE_EARTHQUAKE'].copy()
print(f"1. Baris berstatus 'FUTURE_EARTHQUAKE' yang dibuang : {baris_future} baris")
print(f"   Jumlah baris setelah langkah 1                  : {len(df_bersih)} baris")

# Langkah 2: Jalankan describe() pada kolom lintang dan bujur
print("\n2. Statistik Deskriptif Lintang dan Bujur:")
display(df_bersih[['lintang', 'bujur']].describe())

# Temukan nilai koordinat yang mustahil untuk wilayah Indonesia (acuan: 90° - 145° BT)
koordinat_mustahil = df_bersih[(df_bersih['bujur'] < 90) | (df_bersih['bujur'] > 145)]
print(f"\n   Ditemukan {len(koordinat_mustahil)} baris koordinat bujur di luar batas wilayah Indonesia:")
display(koordinat_mustahil[['id_gempa', 'waktu_utc', 'lintang', 'bujur', 'lokasi']])

# Buang baris yang memiliki nilai bujur mustahil
df_bersih = df_bersih[(df_bersih['bujur'] >= 90) & (df_bersih['bujur'] <= 145)].copy()
print(f"   Jumlah baris setelah membuang koordinat mustahil : {len(df_bersih)} baris")

# Langkah 3: Periksa duplikasi berdasarkan id_gempa
jumlah_duplikasi = df_bersih.duplicated(subset=['id_gempa']).sum()
print(f"\n3. Jumlah duplikasi berdasarkan 'id_gempa'          : {jumlah_duplikasi} baris (tidak ada duplikasi)")

# Langkah 4: Isi nilai kosong pada jenis_lokasi dengan 'Tidak diketahui'
kosong_sebelum = df_bersih['jenis_lokasi'].isnull().sum()
df_bersih['jenis_lokasi'] = df_bersih['jenis_lokasi'].fillna('Tidak diketahui')
kosong_setelah = df_bersih['jenis_lokasi'].isnull().sum()
print(f"\n4. Mengisi nilai kosong pada jenis_lokasi:")
print(f"   - Nilai kosong sebelum imputasi : {kosong_sebelum}")
print(f"   - Nilai kosong setelah imputasi : {kosong_setelah}")

# Laporan akhir ukuran df_bersih
print("\n" + "=" * 60)
print(f"LAPORAN AKHIR: DataFrame df_bersih memiliki {df_bersih.shape[0]} baris dan {df_bersih.shape[1]} kolom.")
print("=" * 60)

1. Baris berstatus 'FUTURE_EARTHQUAKE' yang dibuang : 11 baris
   Jumlah baris setelah langkah 1                  : 3619 baris

2. Statistik Deskriptif Lintang dan Bujur:

           lintang        bujur
count  3619.000000  3619.000000
mean     -3.611050   118.562783
std       3.932918    12.826945
min     -11.780000     1.390000
25%      -7.150000   107.600000
50%      -3.650000   120.550000
75%      -1.155000   126.465000
max       8.530000   143.070000

   Ditemukan 1 baris koordinat bujur di luar batas wilayah Indonesia:

,id_gempa,waktu_utc,lintang,bujur,lokasi
147,20230118223523,2023-01-18 15:35:23,-2.25,1.39,Pusat gempa berada di laut 78 km Baratlaut Jay...

   Jumlah baris setelah membuang koordinat mustahil : 3618 baris

3. Jumlah duplikasi berdasarkan 'id_gempa'          : 0 baris (tidak ada duplikasi)

4. Mengisi nilai kosong pada jenis_lokasi:
   - Nilai kosong sebelum imputasi : 17
   - Nilai kosong setelah imputasi : 0

============================================================
LAPORAN AKHIR: DataFrame df_bersih memiliki 3618 baris dan 13 kolom.
============================================================

### Jawaban dan Analisis B2:
1. **Pembersihan `FUTURE_EARTHQUAKE`:**
   * Ditemukan dan dibuang sebanyak **11 baris** yang bernilai `catatan_kualitas == "FUTURE_EARTHQUAKE"`. Baris-baris ini merupakan kesalahan penanggalan uji coba sistem dengan tanggal masa depan sehingga tidak valid untuk dianalisis. Data berkurang dari 3.630 menjadi 3.619 baris.
2. **Nilai Mustahil pada Lintang dan Bujur:**
   * Berdasarkan hasil `describe()`, nilai minimum bujur tercatat **1,39° BT** yang mustahil untuk wilayah Indonesia (rentang astronomis Indonesia berada pada 90°–145° BT).
   * Pada baris data dengan `id_gempa = 20230118223523`, teks lokasi menyebutkan pusat gempa berada di laut 78 km Barat Laut Jayapura dengan lintang $-2,25$ dan bujur $1,39$. Secara geografis Jayapura terletak di Papua pada bujur sekitar 140,39° BT, sehingga nilai 1,39 adalah salah ketik saat input data.
   * Baris ini dibuang (**1 baris dibuang**), sehingga jumlah data menjadi 3.618 baris.
3. **Pemeriksaan Duplikasi `id_gempa`:**
   * Hasil pemeriksaan duplikasi `id_gempa` bernilai **0**. Seluruh baris data memiliki nomor identitas unik.
4. **Imputasi `jenis_lokasi` dan Jumlah Baris Akhir:**
   * Sebanyak **17 baris** bernilai kosong pada kolom `jenis_lokasi` telah diisi dengan nilai string `"Tidak diketahui"`.
   * DataFrame `df_bersih` yang siap digunakan untuk seluruh analisis memiliki total **3.618 baris** dan **13 kolom**.